name: Python application CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with pytest
      run: |
        pytest

  build:
    runs-on: ubuntu-latest
    needs: test # This job depends on the 'test' job passing
    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false # Only build, don't push yet
        tags: ${{ secrets.DOCKER_USERNAME }}/nasa-apod:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job passing
    if: github.ref == 'refs/heads/main' # Only deploy on pushes to main branch
    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true # Push the image
        tags: ${{ secrets.DOCKER_USERNAME }}/nasa-apod:${{ github.sha }}
